import { ContactsData, CRMContact } from '@/types/contacts-crm';

const daysAgo = (n: number) => new Date(Date.now() - n * 24 * 60 * 60 * 1000).toISOString();
const hoursAgo = (n: number) => new Date(Date.now() - n * 60 * 60 * 1000).toISOString();

const contacts: CRMContact[] = [
  {
    id: 'c1',
    name: 'John Smith',
    company: 'ABC Hospital',
    phone: '+1 415 555 0142',
    email: 'john.smith@abchospital.com',
    industry: 'Healthcare',
    leadScore: 92,
    status: 'booked',
    lastContact: hoursAgo(3),
    assignedAgent: 'Hospital AI Agent',
    nextAction: 'Send proposal',
    tags: ['Hot Lead', 'Enterprise'],
    assignedCampaign: 'Hospital Appointment Reminder',
    lastCallSummary:
      'Confirmed interest in automating appointment reminders across four branches. Requested a proposal and booked a follow-up for Friday.',
    sentiment: 'Positive',
    nextFollowUp: 'Fri, Jul 17 · 11:00 AM',
    notes: [
      { id: 'n1', text: 'Prefers afternoon calls. Decision maker is the Operations Manager.', time: '3 hours ago' },
      { id: 'n2', text: 'Budget confirmed around $1,500/month.', time: '3 hours ago' },
    ],
    conversionProbability: 82,
    aiRecommendations: [
      'Lead score increased by 18%.',
      'Customer opened previous email.',
      'Best calling time is 4 PM.',
      'Recommend assigning Hospital AI Agent.',
    ],
  },
  {
    id: 'c2',
    name: 'Maria Gonzalez',
    company: 'Sunrise Realty',
    phone: '+1 305 555 0188',
    email: 'maria@sunriserealty.com',
    industry: 'Real Estate',
    leadScore: 84,
    status: 'qualified',
    lastContact: daysAgo(1),
    assignedAgent: 'Real Estate AI Agent',
    nextAction: 'Schedule demo',
    tags: ['Hot Lead'],
    assignedCampaign: 'Q3 Seller Outreach',
    lastCallSummary:
      'Interested in AI follow-ups for new listings. Asked about integration with their CRM and pricing tiers.',
    sentiment: 'Positive',
    nextFollowUp: 'Mon, Jul 20 · 2:00 PM',
    notes: [{ id: 'n1', text: 'Manages 40+ active listings. Wants a demo before committing.', time: '1 day ago' }],
    conversionProbability: 71,
    aiRecommendations: [
      'Responds fastest to SMS follow-ups.',
      'Best calling time is 5 PM.',
      'Recommend assigning Real Estate AI Agent.',
    ],
  },
  {
    id: 'c3',
    name: 'David Chen',
    company: 'BrightPath Academy',
    phone: '+1 408 555 0110',
    email: 'd.chen@brightpath.edu',
    industry: 'Education',
    leadScore: 66,
    status: 'interested',
    lastContact: daysAgo(4),
    assignedAgent: 'Enrollment AI Agent',
    nextAction: 'Retry call',
    tags: ['Returning'],
    assignedCampaign: 'Fall Enrollment Drive',
    lastCallSummary:
      'Curious about automating enrollment reminders. Wanted to consult the admissions team before next steps.',
    sentiment: 'Neutral',
    nextFollowUp: 'Wed, Jul 22 · 10:00 AM',
    notes: [{ id: 'n1', text: 'Needs buy-in from admissions director.', time: '4 days ago' }],
    conversionProbability: 48,
    aiRecommendations: [
      'Lead score steady over the last two weeks.',
      'Recommend a value-focused follow-up.',
      'Best calling time is 11 AM.',
    ],
  },
  {
    id: 'c4',
    name: 'Aisha Patel',
    company: 'MediCare Clinics',
    phone: '+1 617 555 0164',
    email: 'aisha.patel@medicare-clinics.com',
    industry: 'Healthcare',
    leadScore: 79,
    status: 'contacted',
    lastContact: daysAgo(2),
    assignedAgent: 'Hospital AI Agent',
    nextAction: 'Follow-up call',
    tags: ['VIP'],
    assignedCampaign: 'Hospital Appointment Reminder',
    lastCallSummary: 'Reviewing options for reducing no-shows. Asked for a case study from a similar clinic.',
    sentiment: 'Positive',
    nextFollowUp: 'Thu, Jul 23 · 3:30 PM',
    notes: [{ id: 'n1', text: 'Send the dental clinic case study.', time: '2 days ago' }],
    conversionProbability: 64,
    aiRecommendations: ['Opened previous email twice.', 'Best calling time is 4 PM.', 'Recommend sending a case study.'],
  },
  {
    id: 'c5',
    name: 'Robert Johnson',
    company: 'Peak Manufacturing',
    phone: '+1 312 555 0137',
    email: 'r.johnson@peakmfg.com',
    industry: 'Manufacturing',
    leadScore: 41,
    status: 'new',
    lastContact: null,
    assignedAgent: 'Unassigned',
    nextAction: 'First call',
    tags: ['Cold Lead'],
    assignedCampaign: 'Unassigned',
    lastCallSummary: 'No calls yet.',
    sentiment: 'Neutral',
    nextFollowUp: 'Not scheduled',
    notes: [],
    conversionProbability: 22,
    aiRecommendations: ['New lead — no history yet.', 'Recommend an introductory call.', 'Best calling time is 10 AM.'],
  },
  {
    id: 'c6',
    name: 'Emily Turner',
    company: 'UrbanNest Realty',
    phone: '+1 206 555 0155',
    email: 'emily@urbannest.com',
    industry: 'Real Estate',
    leadScore: 88,
    status: 'won',
    lastContact: daysAgo(6),
    assignedAgent: 'Real Estate AI Agent',
    nextAction: 'Onboarding',
    tags: ['VIP', 'Returning'],
    assignedCampaign: 'Q3 Seller Outreach',
    lastCallSummary: 'Signed up for the growth plan. Kicking off onboarding next week.',
    sentiment: 'Positive',
    nextFollowUp: 'Tue, Jul 21 · 1:00 PM',
    notes: [{ id: 'n1', text: 'Closed at $1,900/month. Very responsive.', time: '6 days ago' }],
    conversionProbability: 96,
    aiRecommendations: ['Converted customer — focus on onboarding.', 'High referral potential.', 'Best calling time is 1 PM.'],
  },
  {
    id: 'c7',
    name: 'Michael Brooks',
    company: 'ValueMart Retail',
    phone: '+1 469 555 0129',
    email: 'm.brooks@valuemart.com',
    industry: 'Retail',
    leadScore: 54,
    status: 'contacted',
    lastContact: daysAgo(9),
    assignedAgent: 'Retail AI Agent',
    nextAction: 'Re-engage',
    tags: ['Cold Lead'],
    assignedCampaign: 'Loyalty Win-back',
    lastCallSummary: 'Briefly discussed loyalty campaigns. Went quiet after the first call.',
    sentiment: 'Neutral',
    nextFollowUp: 'Not scheduled',
    notes: [{ id: 'n1', text: 'Try a different angle — loyalty ROI.', time: '9 days ago' }],
    conversionProbability: 33,
    aiRecommendations: ['No contact in 9 days.', 'Recommend a re-engagement call.', 'Best calling time is 6 PM.'],
  },
  {
    id: 'c8',
    name: 'Sophia Nguyen',
    company: 'CarePlus Health',
    phone: '+1 503 555 0173',
    email: 'sophia@careplus.com',
    industry: 'Healthcare',
    leadScore: 95,
    status: 'qualified',
    lastContact: hoursAgo(20),
    assignedAgent: 'Hospital AI Agent',
    nextAction: 'Send pricing',
    tags: ['Hot Lead', 'Enterprise'],
    assignedCampaign: 'Hospital Appointment Reminder',
    lastCallSummary: 'Strong intent across 6 locations. Asked for enterprise pricing and a security overview.',
    sentiment: 'Positive',
    nextFollowUp: 'Fri, Jul 17 · 9:30 AM',
    notes: [{ id: 'n1', text: 'Enterprise deal — loop in the sales manager.', time: '20 hours ago' }],
    conversionProbability: 89,
    aiRecommendations: [
      'Lead score increased by 22%.',
      'Highest-value opportunity this week.',
      'Recommend notifying the sales manager.',
      'Best calling time is 9 AM.',
    ],
  },
  {
    id: 'c9',
    name: 'James Wilson',
    company: 'Summit Education',
    phone: '+1 720 555 0198',
    email: 'j.wilson@summitedu.org',
    industry: 'Education',
    leadScore: 72,
    status: 'interested',
    lastContact: daysAgo(3),
    assignedAgent: 'Enrollment AI Agent',
    nextAction: 'Send proposal',
    tags: ['Returning'],
    assignedCampaign: 'Fall Enrollment Drive',
    lastCallSummary: 'Positive about automating parent reminders. Comparing us with one other vendor.',
    sentiment: 'Positive',
    nextFollowUp: 'Mon, Jul 20 · 4:00 PM',
    notes: [{ id: 'n1', text: 'Competing against a legacy vendor — emphasize AI quality.', time: '3 days ago' }],
    conversionProbability: 58,
    aiRecommendations: ['Comparing vendors — send differentiation sheet.', 'Best calling time is 4 PM.'],
  },
  {
    id: 'c10',
    name: 'Olivia Martinez',
    company: 'Prime Properties',
    phone: '+1 786 555 0121',
    email: 'olivia@primeproperties.com',
    industry: 'Real Estate',
    leadScore: 47,
    status: 'lost',
    lastContact: daysAgo(21),
    assignedAgent: 'Real Estate AI Agent',
    nextAction: 'Archive',
    tags: ['Cold Lead'],
    assignedCampaign: 'Q3 Seller Outreach',
    lastCallSummary: 'Chose an in-house solution for now. Open to revisiting next year.',
    sentiment: 'Negative',
    nextFollowUp: 'Not scheduled',
    notes: [{ id: 'n1', text: 'Revisit in Q1. Not a fit right now.', time: '21 days ago' }],
    conversionProbability: 9,
    aiRecommendations: ['Marked lost — low near-term potential.', 'Recommend a nurture sequence.'],
  },
  {
    id: 'c11',
    name: 'Daniel Lee',
    company: 'NorthStar Retail Group',
    phone: '+1 646 555 0190',
    email: 'daniel.lee@northstar.com',
    industry: 'Retail',
    leadScore: 76,
    status: 'booked',
    lastContact: daysAgo(1),
    assignedAgent: 'Retail AI Agent',
    nextAction: 'Confirm meeting',
    tags: ['Hot Lead'],
    assignedCampaign: 'Loyalty Win-back',
    lastCallSummary: 'Booked a demo for the loyalty automation suite. Interested in win-back campaigns.',
    sentiment: 'Positive',
    nextFollowUp: 'Wed, Jul 22 · 12:00 PM',
    notes: [{ id: 'n1', text: 'Wants to see win-back ROI numbers in the demo.', time: '1 day ago' }],
    conversionProbability: 68,
    aiRecommendations: ['Demo booked — prepare ROI figures.', 'Best calling time is 12 PM.'],
  },
  {
    id: 'c12',
    name: 'Grace Kim',
    company: 'Apex Industries',
    phone: '+1 213 555 0146',
    email: 'grace.kim@apexind.com',
    industry: 'Manufacturing',
    leadScore: 61,
    status: 'contacted',
    lastContact: daysAgo(5),
    assignedAgent: 'Unassigned',
    nextAction: 'Qualify',
    tags: ['Enterprise'],
    assignedCampaign: 'Unassigned',
    lastCallSummary: 'Exploring automated supplier check-ins. Needs to understand compliance handling.',
    sentiment: 'Neutral',
    nextFollowUp: 'Thu, Jul 23 · 11:00 AM',
    notes: [{ id: 'n1', text: 'Compliance is the key concern.', time: '5 days ago' }],
    conversionProbability: 44,
    aiRecommendations: ['Recommend assigning an AI agent.', 'Address compliance early.', 'Best calling time is 11 AM.'],
  },
];

export const mockContactsData: ContactsData = {
  contacts,
  kpis: [
    { id: 'total', label: 'Total Contacts', value: '12,480', hint: 'Across all lists', icon: 'total' },
    { id: 'qualified', label: 'Qualified Leads', value: '842', hint: 'Lead score > 75', icon: 'qualified' },
    { id: 'followups', label: 'Follow-ups Due', value: '71', hint: 'Next 24 hours', icon: 'followups' },
    { id: 'appointments', label: 'Appointments', value: '124', hint: 'This month', icon: 'appointments' },
    { id: 'customers', label: 'Customers', value: '43', hint: 'Won this quarter', icon: 'customers' },
    { id: 'score', label: 'Average Lead Score', value: '78', hint: 'Up 4 pts this week', icon: 'score' },
  ],
  pipeline: [
    { id: 'new', label: 'New', count: 4820 },
    { id: 'contacted', label: 'Contacted', count: 3140 },
    { id: 'interested', label: 'Interested', count: 1960 },
    { id: 'qualified', label: 'Qualified', count: 842 },
    { id: 'booked', label: 'Booked', count: 124 },
    { id: 'won', label: 'Won', count: 43 },
  ],
  filterConfig: {
    statuses: [
      { id: 'new', label: 'New' },
      { id: 'contacted', label: 'Contacted' },
      { id: 'interested', label: 'Interested' },
      { id: 'qualified', label: 'Qualified' },
      { id: 'booked', label: 'Booked' },
      { id: 'won', label: 'Won' },
      { id: 'lost', label: 'Lost' },
    ],
    scoreRanges: [
      { id: '0-25', label: '0–25' },
      { id: '26-50', label: '26–50' },
      { id: '51-75', label: '51–75' },
      { id: '76-100', label: '76–100' },
    ],
    industries: [
      { id: 'Healthcare', label: 'Healthcare' },
      { id: 'Real Estate', label: 'Real Estate' },
      { id: 'Education', label: 'Education' },
      { id: 'Retail', label: 'Retail' },
      { id: 'Manufacturing', label: 'Manufacturing' },
    ],
    tags: [
      { id: 'VIP', label: 'VIP' },
      { id: 'Cold Lead', label: 'Cold Lead' },
      { id: 'Hot Lead', label: 'Hot Lead' },
      { id: 'Returning', label: 'Returning' },
      { id: 'Enterprise', label: 'Enterprise' },
    ],
    lastContacted: [
      { id: 'today', label: 'Today' },
      { id: 'yesterday', label: 'Yesterday' },
      { id: '7d', label: 'Last 7 Days' },
      { id: '30d', label: 'Last 30 Days' },
    ],
  },
};

export const emptyContactsData: ContactsData = {
  ...mockContactsData,
  contacts: [],
};
