"""Add agent model and link to campaign

Revision ID: 38637014af2c
Revises: edec0377a075
Create Date: 2026-05-10 21:42:37.613168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38637014af2c'
down_revision: Union[str, Sequence[str], None] = 'edec0377a075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('agent_id', sa.UUID(), nullable=True))
    op.alter_column('campaigns', 'business_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('campaigns', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'campaigns', 'agents', ['agent_id'], ['id'])
    op.alter_column('contacts', 'business_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('contacts', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('contacts', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('contacts', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('contacts', 'business_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.alter_column('campaigns', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('campaigns', 'business_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('campaigns', 'agent_id')
    # ### end Alembic commands ###
