"""initial schema sync

Revision ID: 5bf919ca888d
Revises: 
Create Date: 2026-05-05 21:47:24.328521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bf919ca888d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('description', sa.Text(), nullable=True))
    op.execute("DO $$ BEGIN CREATE TYPE campaignstatus AS ENUM ('draft', 'scheduled', 'active', 'paused', 'completed', 'cancelled'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.add_column('campaigns', sa.Column('status', sa.Enum('draft', 'scheduled', 'active', 'paused', 'completed', 'cancelled', name='campaignstatus'), nullable=False, server_default='draft'))
    op.add_column('campaigns', sa.Column('ai_prompt', sa.Text(), nullable=True))
    op.add_column('campaigns', sa.Column('ai_voice', sa.String(length=100), nullable=True))
    op.add_column('campaigns', sa.Column('max_retries', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('campaigns', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('campaigns', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # op.alter_column('campaigns', 'business_id',
    #            existing_type=sa.UUID(),
    #            nullable=False)
    # op.alter_column('campaigns', 'name',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    op.add_column('contacts', sa.Column('company', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('tags', sa.String(length=500), nullable=True))
    op.add_column('contacts', sa.Column('notes', sa.Text(), nullable=True))
    op.execute("DO $$ BEGIN CREATE TYPE contactstatus AS ENUM ('new', 'contacted', 'interested', 'not_interested', 'no_answer', 'callback', 'converted', 'do_not_call'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.add_column('contacts', sa.Column('status', sa.Enum('new', 'contacted', 'interested', 'not_interested', 'no_answer', 'callback', 'converted', 'do_not_call', name='contactstatus'), nullable=False, server_default='new'))
    op.add_column('contacts', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('contacts', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # op.alter_column('contacts', 'business_id',
    #            existing_type=sa.UUID(),
    #            nullable=False)
    # op.alter_column('contacts', 'name',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.alter_column('contacts', 'phone_number',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    op.drop_constraint(op.f('contacts_campaign_id_fkey'), 'contacts', type_='foreignkey')
    op.create_foreign_key(None, 'contacts', 'businesses', ['business_id'], ['id'])
    op.drop_column('contacts', 'campaign_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('campaign_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.create_foreign_key(op.f('contacts_campaign_id_fkey'), 'contacts', 'campaigns', ['campaign_id'], ['id'])
    op.alter_column('contacts', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('contacts', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('contacts', 'business_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('contacts', 'updated_at')
    op.drop_column('contacts', 'created_at')
    op.drop_column('contacts', 'status')
    op.drop_column('contacts', 'notes')
    op.drop_column('contacts', 'tags')
    op.drop_column('contacts', 'company')
    op.alter_column('campaigns', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('campaigns', 'business_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('campaigns', 'updated_at')
    op.drop_column('campaigns', 'created_at')
    op.drop_column('campaigns', 'scheduled_at')
    op.drop_column('campaigns', 'max_retries')
    op.drop_column('campaigns', 'ai_voice')
    op.drop_column('campaigns', 'ai_prompt')
    op.drop_column('campaigns', 'status')
    op.drop_column('campaigns', 'description')
    # ### end Alembic commands ###
