"""Add fields to call_logs

Revision ID: fb1c8ed4c88a
Revises: 5bf919ca888d
Create Date: 2026-05-05 22:33:38.827698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb1c8ed4c88a'
down_revision: Union[str, Sequence[str], None] = '5bf919ca888d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_logs', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('call_logs', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('call_logs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # op.alter_column('campaigns', 'business_id',
    #            existing_type=sa.UUID(),
    #            nullable=False)
    # op.alter_column('campaigns', 'name',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.alter_column('contacts', 'business_id',
    #            existing_type=sa.UUID(),
    #            nullable=False)
    # op.alter_column('contacts', 'name',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.alter_column('contacts', 'phone_number',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('contacts', 'phone_number',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # op.alter_column('contacts', 'name',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # op.alter_column('contacts', 'business_id',
    #            existing_type=sa.UUID(),
    #            nullable=True)
    # op.alter_column('campaigns', 'name',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # op.alter_column('campaigns', 'business_id',
    #            existing_type=sa.UUID(),
    #            nullable=True)
    op.drop_column('call_logs', 'updated_at')
    op.drop_column('call_logs', 'created_at')
    op.drop_column('call_logs', 'duration')
    # ### end Alembic commands ###
